In [1]:
import numpy as np
import math

In [2]:
print("Interpolasi newton")

Interpolasi newton


In [151]:
orde = 4
n = orde - 1
x = np.array([8,9,9.5,11])
y = np.array([2.079442, 2.197225, 2.251292, 2.397895])
ST = np.zeros((orde,orde))

In [152]:
"Simpan y[i] pada kolom ke nol"
ST

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [153]:
for i in range(orde):
  ST[i,0] = y[i]

In [154]:
"Membuat tabel selisih terbagi"

'Membuat tabel selisih terbagi'

In [150]:
(ST[1,0]-ST[0,0])/(x[1]-x[0])

0.1177830000000002

In [102]:
ST[1,0]-ST[0,0]

0.1172

In [103]:
i = 0
k = 1
(ST[i+1,k-1]-ST[i,k-1])/(x[i+k]-x[i])

0.1171875

In [155]:
for k in range(1,orde):
  for i in range(0,orde-k):
    #ST[i,k] = (ST[i+1,k-1]-ST[i,k-i])/(x[i+k]-x[i])
    ST[i,k] = (ST[i+1,k-1]-ST[i,k-1])/(x[i+k]-x[i])

In [168]:
jumlah = ST[0,0]
x_input = 9.2
for i in range(1,n):
  suku = ST[0,i]
  for k in range(0,i):
    suku = suku*(x_input-x[k])
  jumlah+=suku
  print(jumlah)
newton = jumlah
print(newton)

2.2207816
2.21923776
2.21923776


In [210]:
def inperpolasi_newton(x,y,orde,x_input):
  ST = np.zeros((orde,orde))
  n = orde - 1
  for i in range(orde):
    ST[i,0] = y[i]

  for k in range(1,orde):
    for i in range(0,orde-k):
      #ST[i,k] = (ST[i+1,k-1]-ST[i,k-i])/(x[i+k]-x[i])
      ST[i,k] = (ST[i+1,k-1]-ST[i,k-1])/(x[i+k]-x[i])
  print(ST)

  jumlah = ST[0,0]
  for i in range(1,n):
    suku = ST[0,i]
    for k in range(0,i):
      suku = suku*(x_input-x[k])
    jumlah = jumlah + suku
  newton = jumlah
  return newton

In [208]:
x = np.array([0, 1, 2, 3, 4])
y = np.cos(x)
y1 = np.array([1.000, 0.5403, -0.4161, -0.9900, -0.6536 ])
print(y)
print(y1)

[ 1.          0.54030231 -0.41614684 -0.9899925  -0.65364362]
[ 1.      0.5403 -0.4161 -0.99   -0.6536]


In [209]:
inperpolasi_newton(x,y,5,2.5)

[[ 1.         -0.45969769 -0.24837572  0.14655916 -0.01465683]
 [ 0.54030231 -0.95644914  0.19130174  0.08793184  0.        ]
 [-0.41614684 -0.57384566  0.45509727  0.          0.        ]
 [-0.9899925   0.33634888  0.          0.          0.        ]
 [-0.65364362  0.          0.          0.          0.        ]]
-0.1492442353296506
-1.0806532008610665
-0.8058547850343788


-0.8058547850343788

In [182]:
np.cos(2.5)-inperpolasi_newton(x,y,5,2.5)

[[ 1.         -0.24483488 -0.42972564  0.11010396  0.02159196]
 [ 0.87758256 -0.67456051 -0.2645697   0.15328789  0.        ]
 [ 0.54030231 -0.93913021 -0.03463787  0.          0.        ]
 [ 0.0707372  -0.97376808  0.          0.          0.        ]
 [-0.41614684  0.          0.          0.          0.        ]]


0.13379205678324102

In [173]:
inperpolasi_newton(x,y1,5,2.5)

[[ 1.         -0.4597     -0.24835     0.14653333 -0.01464167]
 [ 0.5403     -0.9564      0.19125     0.08796667  0.        ]
 [-0.4161     -0.5739      0.45515     0.          0.        ]
 [-0.99        0.3364      0.          0.          0.        ]
 [-0.6536      0.          0.          0.          0.        ]]


-0.8058125