In [1]:
import numpy as np

In [2]:
print("backward substitution")

backward substitution


In [35]:
n = 3

In [86]:
A = np.array([(4,-1,2,3),(0,-2,7,-4),(0,0,6,5),(0,0,0,3)])

In [87]:
B = np.array([(20),(-7),(4),(6)]).reshape(n+1,1)

In [43]:
B

array([[20],
       [-7],
       [ 4],
       [ 6]])

In [52]:
x = np.zeros((n+1,1))
x

array([[0.],
       [0.],
       [0.],
       [0.]])

In [83]:
"Teknik Penyulihan mundur"
x[n] = B[n]/A[n,n]
for k in range(n-1,-1,-1):
  sigma = 0
  for j in range(k+1,n+1,1):
    sigma = sigma + A[k,j]*x[j]
  x[k] = (B[k] - sigma)/A[k,k]

In [77]:
x

array([[ 3.],
       [-4.],
       [-1.],
       [ 2.]])

In [95]:
def sulih_mundur(A,B,orde):
  n = orde-1
  x = np.zeros((n+1,1))
  "Teknik Penyulihan mundur"
  x[n] = B[n]/A[n,n]
  for k in range(n-1,-1,-1):
    sigma = 0
    for j in range(k+1,n+1,1):
      sigma = sigma + A[k,j]*x[j]
    x[k] = (B[k] - sigma)/A[k,k]
  return x

In [149]:
n = orde-1

In [150]:
sulih_mundur(A,B,4)

array([[ 3.],
       [-4.],
       [-1.],
       [ 2.]])

In [151]:
a = np.array([(2,3,-1),(4,4,-3),(-2,3,-1)])
orde = 3
a

array([[ 2,  3, -1],
       [ 4,  4, -3],
       [-2,  3, -1]])

In [152]:
b = np.array([(5),(3),(1)]).reshape(orde,1)
b

array([[5],
       [3],
       [1]])

In [153]:
for k in range(0,n):
  for i in range(k+1,n+1):
    m = a[i,k]/a[k,k]
    for j in range(k,n+1):
      a[i,j] = a[i,j] - (m*a[k,j])
    b[i] = b[i]-(m*b[k])
sulih_mundur(a,b,orde)

array([[1.],
       [2.],
       [3.]])